export const projects = [
  {
    id: "ai-assistant-ui",
    title: "AI Assistant UI",
    desc: "A sleek conversational interface powered by OpenAI API, designed for real-time responses and intuitive interaction.",
    tech: ["React", "Tailwind", "Node.js"],
    link: "#",
  },
  {
    id: "portfolio-website",
    title: "Portfolio Website",
    desc: "Responsive developer portfolio featuring modern design, animations, and optimized performance.",
    tech: ["Next.js", "Framer Motion", "Tailwind CSS"],
    link: "#",
  },
  {
    id: "data-dashboard",
    title: "Data Dashboard",
    desc: "Interactive analytics dashboard presenting live charts and actionable insights from API data.",
    tech: ["React", "Recharts", "Express"],
    link: "#",
  },
  {
    id: "task-manager",
    title: "Task Manager",
    desc: "Minimalist full-stack productivity app to track tasks efficiently with intuitive UX.",
    tech: ["MongoDB", "React", "Tailwind"],
    link: "#",
  },
  {
    id: "trackademic",
    title: "Trackademic",
    desc: "Comprehensive platform to manage student records, attendance, grades, and staff operations seamlessly.",
    tech: ["Tailwind", "JavaScript", "Node.js"],
    link: "#",
  },
  {
    id: "quiz-master-1",
    title: "Quiz Master",
    desc: "Interactive web app for creating, taking, and sharing quizzes in real-time with dynamic feedback.",
    tech: ["Node.js", "React", "Firebase"],
    link: "#",
  },
  {
    id: "quiz-master-2",
    title: "Quiz Master",
    desc: "Interactive web app for creating, taking, and sharing quizzes in real-time with dynamic feedback.",
    tech: ["Node.js", "React", "Firebase"],
    link: "#",
  },
  {
    id: "lode-management",
    title: "Lode Management",
    desc: "Comprehensive web app for managing, tracking, and optimizing lode operations with real-time analytics and reporting.",
    tech: ["Node.js", "React", "MongoDB"],
    link: "#",
  },
];
